# Generated by Django 6.0.7 on 2026-07-22 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveIntegerField()),
                ('totals', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('current_lat', models.FloatField(blank=True, null=True)),
                ('current_lng', models.FloatField(blank=True, null=True)),
                ('pickup_location', models.CharField(max_length=255)),
                ('pickup_lat', models.FloatField(blank=True, null=True)),
                ('pickup_lng', models.FloatField(blank=True, null=True)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('dropoff_lat', models.FloatField(blank=True, null=True)),
                ('dropoff_lng', models.FloatField(blank=True, null=True)),
                ('current_cycle_used_hrs', models.FloatField()),
                ('distance_miles', models.FloatField(blank=True, null=True)),
                ('driving_hours', models.FloatField(blank=True, null=True)),
                ('duty_days', models.PositiveIntegerField(blank=True, null=True)),
                ('route_geometry', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('planned', 'Planned'), ('in_transit', 'In transit'), ('completed', 'Completed')], default='planned', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DutySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('OFF', 'Off duty'), ('SB', 'Sleeper berth'), ('D', 'Driving'), ('ON', 'On duty (not driving)')], max_length=3)),
                ('start_hr', models.FloatField()),
                ('end_hr', models.FloatField()),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('log_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='segments', to='trips.logsheet')),
            ],
            options={
                'ordering': ['start_hr'],
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('pickup', 'Pickup'), ('dropoff', 'Dropoff'), ('fuel', 'Fuel'), ('rest_break', '30-minute break'), ('sleeper_berth', 'Sleeper berth rest'), ('restart', '34-hour restart')], max_length=20)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('at_mile', models.FloatField(blank=True, null=True)),
                ('duration_hrs', models.FloatField()),
                ('sequence', models.PositiveIntegerField()),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='trips.trip')),
            ],
            options={
                'ordering': ['sequence'],
            },
        ),
        migrations.AddField(
            model_name='logsheet',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='log_sheets', to='trips.trip'),
        ),
        migrations.AlterUniqueTogether(
            name='logsheet',
            unique_together={('trip', 'day_number')},
        ),
    ]
