# Generated by Django 6.0.7 on 2026-07-24 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='status',
        ),
        migrations.AlterField(
            model_name='trip',
            name='current_cycle_used_hrs',
            field=models.FloatField(default=0.0),
        ),
    ]
